name: laboratory-OTL

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686" # Jaeger UI
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=study-api
      - NODE_ENV=development
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=study
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - TZ=America/Sao_Paulo
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - otel-collector
    container_name: api
    user: "root"
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sincroniza o fuso horário do host
      - /etc/timezone:/etc/timezone:ro # Sincroniza a configuração de timezone do host
      - ./api:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
