receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  exporters:
    debug:
      verbosity: detailed

    otlp:
      endpoint: jaeger:4317
      tls:
        insecure: true

    otlphttp/tempo:
        endpoint: http://tempo:4319
        tls:
          insecure: true

processors:
  batch: {}

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
